---
title: "CodeBook"
author: "Clare Moffatt"
date: "6/8/2020"
output: html_document
---

## Project Description
Project involving preparing a set of tidy data on wearable computing.

##Study design and data processing
The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. 

###Collection of the raw data
Using its embedded accelerometer and gyroscope, the researchers captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. 

##Creating the tidy datafile
The run_analysis.R script transforms the data into the tidy data format in "tidy_data.txt". The readme document describes the ocde in greater detail. This occurs in the following steps:
1. Download and unzip the data in UCI HAR Dataset
2. Merge the training and the test sets to create one data set.
3. Extract only the measurements on the mean and standard deviation for each measurement.
4. Assign descriptive activity names to name the activities in the data set
5. Appropriately label the data set with descriptive variable names.
6. Creates an independent tidy data set with the average of each variable for each activity and each subject.

##Variables
Dimensions of the dataset: 180 observations of 88 variables
Summary of the data: Contains average measurements (includes 88 variables) for each subject and type of walking

Variables present in the dataset:
- Subject: the subject who performed the activity for each window sample. Its range is from 1 to 30. 
- Activity: WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING
- Measurement variables are broken down across the following categories:
    - Time domain or frequency domain
    - Accelerometer or Gyroscope
    - 3-axial signals in the X, Y and Z directions
    - Mean and Standard Deviation
- Note on units:
    - The acceleration signal from the smartphone accelerometer X axis in standard gravity units 'g'.
    - The angular velocity vector measured by the gyroscope for each window sample has units in radians/second. 
    - Features are normalized and bounded within [-1,1]
